### ISSUE TITLE
Recomendação do aplicativo CittaMobi

### ISSUE THREAD

**Issue by leilacintrao** [jonathangouvea/GuiaEnC#1]
Na seção sobre ônibus, talvez seja interessante informar sobre o aplicativo [CittaMobi](https://play.google.com/store/apps/details?id=br.com.cittabus), que mostra os pontos e linhas e costuma ser preciso nos horários.

**Comment by jonathangouvea** [comment]
Uma boa ideia! Se quiser pode escrever e colocar lá, se não eu coloco amanhã ou depois!
