### ISSUE TITLE
Refatorar para um Framework

### ISSUE THREAD

**Issue by henrycunh** [jonathangouvea/GuiaEnC#6]
ficar mais fácil contribuir/fazer manutenção e tal

**Comment by jonathangouvea** [comment]
Não acho necessário mudar para um Framework... O design pode ser melhorado mas não está tão cru assim, então acho que daria muito trabalho e não é problema não usar um Framework

**Comment by henrycunh** [comment]
eu faço aí cê vê se piorou pra contribuir e tal, vou usar como exemplo num talk também se tiver de boa
